### ISSUE TITLE
Path must be a string.

### ISSUE THREAD

**Issue by Hoto-Cocoa** [DasWolke/discordbot#95]
```root@DO2:~/discordrem# nodejs index.js
info: Starting Init of Bot!
2017-01-09T17:21:45.738Z - info: Starting Errorhandling!
2017-01-09T17:21:46.129Z - info:  messageCacheMaxSize=200, messageCacheLifetime=600, messageSweepInterval=1200, disableEveryone=true, fetchAllMembers=false, disabledEvents=[typingStart, typingStop, guildMemberSpeaking]
2017-01-09T17:21:46.541Z - info: Connecting to DB
2017-01-09T17:21:46.553Z - info: Logging in...
2017-01-09T17:21:46.574Z - info: Logged in successfully
2017-01-09T17:21:46.574Z - info: Bot finished Init
Shard:undefined BLOCKED FOR 349ms
Shard:undefined BLOCKED FOR 24ms
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.<anonymous> (/root/discordrem/node_modules/youtube-dl/lib/youtube-dl.js:19:71)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/discordrem/utility/youtube/youtube-child.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/discordrem/utility/youtube/helper.js:6:10)    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/discordrem/commands/addToQueue.js:8:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at fs.readdir (/root/discordrem/utility/cmdManager.js:73:31)
    at FSReqWrap.oncomplete (fs.js:112:15)
root@DO2:~/discordrem#```

**Comment by DasWolke** [comment]
Hey, you have to have youtube-dl installed and added in path. Once you did that, run npm rebuild and then it should work fine

**Comment by Hoto-Cocoa** [comment]
Thx! Fixed!!
