### ISSUE TITLE
When try osu! music add to queue, get error.

### ISSUE THREAD

**Issue by Hoto-Cocoa** [DasWolke/discordbot#96]
![Discord Screen](https://puu.sh/th0uo/9e9b7f2cf5.png)
Discord Screen, And Error Log.
```
2017-01-10T00:16:20.609Z - info: cb.qa https://osu.ppy.sh/b/1027369
Shard:undefined BLOCKED FOR 258ms
Shard:undefined BLOCKED FOR 51ms
2017-01-10T00:16:22.675Z - info: /root/discordrem/-
Shard:undefined BLOCKED FOR 67ms
Shard:undefined BLOCKED FOR 14ms
Shard:undefined BLOCKED FOR 16ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: invalid signature: 0x4f44213c
    at /root/discordrem/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
root@DO2:~/discordrem#
```

**Comment by DasWolke** [comment]
Well. You are still using the version 1 code of rem which is outdated and does not not updated anymore. I would therefore suggest using the code from the rem-v2 repo.

**Comment by Hoto-Cocoa** [comment]
OK :)
